name: Update Predictions

on:
  schedule:
    - cron: "*/10 * * * *"
  

permissions:
  contents: write
# add this comment
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials file
        run: echo '${{ secrets.GOOGLE_CREDS }}' > credentials.json

      - name: Run script
        run: python main.py

      - name: Commit CSVs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
          git add masterfile/
          git add individual/
      
          git commit -m "Update predictions" || echo "No changes"
          git push
