name: Schedule workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Log time
        run:  |
          current_date_time-$(date)
          echo "Current data and time: $current_date_time"
